# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "ce1a42f7-5c62-4cbe-834d-ca1f4e0bab68",
# META       "default_lakehouse_name": "gpgOpDataStore",
# META       "default_lakehouse_workspace_id": "f097d258-1737-4f0b-8e09-09197805d11b",
# META       "known_lakehouses": [
# META         {
# META           "id": "ce1a42f7-5c62-4cbe-834d-ca1f4e0bab68"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Welcome to your new notebook
# Type here in the cell editor to add code!


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df = spark.sql("SELECT * FROM gpgOpDataStore.dbo.Movies LIMIT 1000")
display(df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

def clean_data(df):
    # Rename column 'Prop_0' to 'Movie'
    df = df.withColumnRenamed('Prop_0', 'Movie')
    # Rename column 'Prop_1' to 'Title'
    df = df.withColumnRenamed('Prop_1', 'Title')
    # Rename column 'Prop_2' to 'Generes'
    df = df.withColumnRenamed('Prop_2', 'Generes')
    # Rename column 'Prop_3' to 'Year'
    df = df.withColumnRenamed('Prop_3', 'Year')
    # Rename column 'Prop_4' to 'Rating'
    df = df.withColumnRenamed('Prop_4', 'Rating')
    # Rename column 'Prop_5' to 'RottenTomato'
    df = df.withColumnRenamed('Prop_5', 'RottenTomato')
    return df

df_clean = clean_data(df)
display(df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
